// First migration: the tables, then the price hypertable and its compression, generated by @timescaledb/core
// (the official TimescaleDB TypeScript library; its TypeORM package needs decorators, see entities.ts).
import { TimescaleDB } from "@timescaledb/core";
import type { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePriceSchema1790668800000 implements MigrationInterface {
  name = "CreatePriceSchema1790668800000";

  /**
   * Compression measured on 60 simulated days of Magic + Star Wars Unlimited (2026-09-29): about 3.3 MB per day.
   * Rows are sorted by product then day, so a price that does not move compresses to almost nothing; the library
   * requires a segment column, and "game" (few values) keeps large compressed batches. The policy compresses the
   * chunks (7 days each) once they are older than 7 days.
   */
  private readonly hypertable = TimescaleDB.createHypertable("price", {
    by_range: { column_name: "day" },
    compression: {
      compress: true,
      compress_orderby: "id_product, day",
      compress_segmentby: "game",
      policy: { schedule_interval: "7 days" },
    },
  });

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(TimescaleDB.createExtension().up().build());
    await queryRunner.query(`
      CREATE TABLE product (
        id_product integer PRIMARY KEY,
        game smallint NOT NULL,
        name text NOT NULL,
        category text NOT NULL,
        id_expansion integer NOT NULL,
        id_metacard integer NOT NULL
      )`);
    await queryRunner.query(`
      CREATE TABLE price (
        day date NOT NULL,
        id_product integer NOT NULL,
        game smallint NOT NULL,
        low double precision, trend double precision, avg double precision,
        avg1 double precision, avg7 double precision, avg30 double precision,
        low_foil double precision, trend_foil double precision, avg_foil double precision,
        avg1_foil double precision, avg7_foil double precision, avg30_foil double precision,
        PRIMARY KEY (id_product, day)
      )`);
    await queryRunner.query(`
      CREATE TABLE imported_file (
        feed text NOT NULL,
        day date NOT NULL,
        rows integer NOT NULL,
        imported_at timestamptz NOT NULL,
        PRIMARY KEY (feed, day)
      )`);
    await queryRunner.query(this.hypertable.up().build());
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("DROP TABLE imported_file");
    await queryRunner.query("DROP TABLE price");
    await queryRunner.query("DROP TABLE product");
  }
}
